config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :sources, only: [:show] do
    resources :activities, only: [:create, :index, :show, :destroy] do
      put :sync, on: :member
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get 'users/current', to: 'users/registrations#edit', as: :edit_user
    put 'users/current' => 'users/registrations#update', as: :user
  end

  resources :identities, only: [:destroy]
  resources :guests, only: [:create]
  get 'contact' => 'application#contact'
  root 'application#home'

end

app/models/guest.rb
class Guest
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :email, type: String
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  def create
    @guest = Guest.new guest_params

    if @guest.save
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /guests/1
  def update
    if @guest.update(guest_params)
      redirect_to @guest, notice: 'Guest was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /guests/1
  def destroy
    @guest.destroy
    redirect_to guests_url, notice: 'Guest was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    @guest = Guest.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def guest_params
    params.require(:guest).permit(:name, :email)
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= simple_form_for(@guest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>