config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :sources, only: [:show] do
    resources :activities, only: [:create, :index, :show, :destroy] do
      put :sync, on: :member
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get 'users/current', to: 'users/registrations#edit', as: :edit_user
    put 'users/current' => 'users/registrations#update', as: :user
  end

  resources :identities, only: [:destroy]
  resources :guests, only: [:create]
  get 'contact' => 'application#contact'
  root 'application#home'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  include Mongoid::Timestamps

  TYPES = %w[Running Cycling Walking Swimming Hiking Snowboarding Skating Stairmaster Elliptical Skiing Paddling Spinning Kayaking].freeze

  belongs_to :user
  field :provider
  belongs_to :identity

  field :uuid, type: String
  field :strava_uuid, type: String
  field :runkeeper_uuid, type: String
  field :type, type: String
  field :api, type: Boolean
  field :duration, type: Integer
  field :distance, type: Integer
  field :start_time, type: DateTime
  field :utc_offset, type: Integer, default: 0
  field :climb, type: Integer
  field :syncs, type: Hash, default: {}

  embeds_many :points

  validates :user, :uuid, :provider, presence: true
  validates :type, :duration, :distance, :start_time, presence: true
  validates :provider, inclusion: { in: Identity::PROVIDERS }

  validates_uniqueness_of :uuid, scope: :user
  validates_uniqueness_of :user, scope: %i[type distance duration start_time]

  scope :duplicate, (lambda { |a|
                        if a.provider == 'runkeeper'
                          where(provider: 'strava', runkeeper_uuid: a.uuid)
                        else
                          where(provider: 'runkeeper', strava_uuid: a.uuid)
                        end
                      })

  scope :with_drift, (lambda { |a|
                        t = type?(a)
                        t = t.duration_with_drift(a)
                        t = t.distance_with_drift(a)
                        t = t.start_time_with_drift(a)
                        t
                      })
  scope :type?, (->(a) { where(type: a.type) })
  scope :duration_with_drift, (lambda { |a|
                                 drift = 60 # seconds
                                 where(:duration.gt => a.duration - drift,
                                       :duration.lt => a.duration + drift)
                               })
  scope :distance_with_drift, (lambda { |a|
                                 drift = 100 # meters
                                 where(:distance.gt => a.distance - drift,
                                       :distance.lt => a.distance + drift)
                               })
  scope :start_time_with_drift, (lambda { |a|
                                   drift = 60.seconds
                                   where(:start_time.gt => a.start_time - drift,
                                         :start_time.lt => a.start_time + drift)
                                 })

  def source
    provider
  end

  def synched_with?(source)
    source_uuid = send "#{source}_uuid"
    !source_uuid.blank?
  end

  def on_sync(source, uuid)
    self.syncs[source.to_s] = uuid
    self.send "#{source}_uuid=", uuid
    save
  end

  def start_time_local
    start_time.new_offset "#{utc_offset>0 ? '+' : '-'}#{utc_offset}"
  end

  def start_time_local=(time:, utc_offset: 0)
    utc_offset ||= 0
    self.start_time = DateTime.parse(time)
    self.start_time -= Rational(utc_offset, 24)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :current_source
  before_action :collection, only: [:index, :create]
  before_action :current_activity, only: [:sync, :show, :destroy]

  helper_method :current_source

  def create
    options = Jobs::Activities.payload current_identity
    enqueue Jobs::Activities, options

    redirect_to source_activities_path current_source
  end

  def index
  end

  def show
  end

  def destroy
    current_activity.destroy

    redirect_to source_activities_path current_source
  end

  def sync
    payload = Jobs::Activity.payload current_activity
    # enqueue Jobs::Activity, payload
    Jobs::Activity.do_perform payload.stringify_keys

    redirect_to source_activities_path current_source
  end

  private

  def current_source
    @source ||= params[:source_id]
  end

  def current_identity
    @identity ||= current_user.identity current_source
  end

  def collection
    @activities ||= current_user.activities.where(provider: current_source).order_by(:start_time.desc).limit 50
  end

  def current_activity
    @activity = current_user.activities.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:duration, :distance)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def distance(activity)
    "#{activity.distance} m"
  end

  def duration(activity)
    ChronicDuration.output(activity.duration)
  end

  def start_time(activity)
    tz = current_user.time_zone || 'UTC'
    t = activity.start_time.in_time_zone tz
    t.to_s
  end
end

app/views/activities/_form.html.haml
= form_for @activity, :html => { :class => "form-horizontal", :role => "form" } do |f|
  -if @activity.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{:type => "button", :data => {:dismiss => "alert"} }
        span{:aria => {:hidden => "true"} } &times;
        span.sr-only Close
      %h4= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"

      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :source, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :source, :class => 'form-control'
  .form-group
    = f.label :uuid, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :uuid, :class => 'form-control'
  .form-group
    = f.label :type, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :type, :class => 'form-control'
  .form-group
    = f.label :duration, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :duration, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/activities/edit.html.haml
.page-header
  = link_to activities_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @activity, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing activity

= render 'form'

app/views/activities/index.html.haml
.page-header
  = link_to source_activities_path(current_source), id: 'pull', class: 'btn btn-primary', method: :post do
    %span.glyphicon.glyphicon-refresh
    Refresh
  %h1
    = "Listing #{current_source.titleize} activities"
    %a{href: "#", title: "Last 50 activities."}
      %i.glyphicon.glyphicon-info-sign

%div.alert.alert-info{role: "alert"}
  = "Synchronizing with #{current_source.titleize} every hour."
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Source
        %th Uuid
        %th Type
        %th Duration
        %th Distance
        %th Start time
        %th In sync with
        %th

    %tbody
      - @activities.each do |activity|
        %tr
          %td.source= activity.source
          %td.uuid= activity.uuid
          %td.type= activity.type
          %td.duration= duration activity
          %td.distance= distance activity
          %td.start_time= start_time activity
          %td.syncs= activity.syncs
          %td
            = link_to 'Show', source_activity_path(current_source, activity)
            |
            = link_to 'Sync', sync_source_activity_path(current_source, activity), method: :put

app/views/activities/new.html.haml
.page-header
  = link_to activities_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New activity

= render 'form'

app/views/activities/show.html.haml
.page-header
  - if current_user.admin
    = link_to source_activity_path(current_source, @activity), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' do
      %span.glyphicon.glyphicon-remove
        Delete
  = link_to source_activities_path(current_source), :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 Show activity

%dl.dl-horizontal
  %dt Source:
  %dd= @activity.source
  %dt Uuid:
  %dd= @activity.uuid
  %dt Type:
  %dd= @activity.type
  %dt Duration:
  %dd= ChronicDuration.output(@activity.duration)
  %dt Distance:
  %dd= "#{@activity.distance} m"
  %dt Start time:
  %dd= @activity.start_time.httpdate
  %dt UTC offset:
  %dd= ChronicDuration.output(@activity.utc_offset * 60 * 60)