config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  mount ResqueWeb::Engine => '/resque'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :sources, only: [:show] do
    resources :activities, only: [:create, :index, :show, :destroy] do
      put :sync, on: :member
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get 'users/current', to: 'users/registrations#edit', as: :edit_user
    put 'users/current' => 'users/registrations#update', as: :user
  end

  resources :identities, only: [:destroy]
  resources :guests, only: [:create]
  get 'contact' => 'application#contact'
  root 'application#home'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{content: "actihunt.com", name: "author"}
    %meta{content: "Syncronize your sport activities", name: "description"}
    %meta{content: "sport fitness activities strava runkeeper garmin endomondo sportstracker running biking swiming walking", name: "keywords"}
    %meta{"http-equiv" => "refresh", :content => "60"}
    %title ActiHunt

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a{href: '/'}
            %img{src: '/images/logo.jpg', height: '50', alt: 'logo'}

        #navbar.collapse.navbar-collapse
          - if current_user
            %ul.nav.navbar-nav
              - current_user.identities.each do |identity|
                = content_tag :li, class: "#{identity_class(identity)}" do
                  %a{href: "/sources/#{identity.provider}/activities"}
                    = identity.provider.titleize
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{href: '/contact'} Contact
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              %li
                %a{id: 'account', href: "#{edit_user_path}"}
                  %i.glyphicon.glyphicon-user
                  = current_user.name
              %li
                %a{id: 'sign_out', href: "#{sign_out_path}"}
                  %i.glyphicon.glyphicon-lock
                  Logout
    .container
      .row
        .span4
          -# left pane
        .span8
          - flash.each do |name, msg|
            = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do
              %button.close{type: "button", data: { dismiss: "alert"}}
                %span{aria: {hidden: 'true'} } &times;
                %span.sr-only Close
              = msg
          = yield
    %footer.footer
      %nav.navbar.navbar-inverse{:role => "navigation"}
        .container
          .row
            .col-lg-12
              %br/
              %a.pull-right
                  ©2019 ActiHunt
                %sup TM
              %br/
    = render 'freshdesk'